### ISSUE TITLE
Installation / Update - Fehler

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#126]
Die Neuinstallation funktioniert bei mir nicht.
Es kommt ein leeres PS Fenster.

Beim Update kommt folgende Meldung und funktioniert dann auch nicht mehr...

```
2020-05-03 23:08:22.551  INFO 17132 --- [           main] com.dude.dms.Application                 : Started Application in 10.233 seconds (JVM running for 10.953)
2020-05-03 23:08:22.609  INFO 17132 --- [           main] com.dude.dms.updater.UpdateChecker       : Suche nach neuer Version
2020-05-03 23:08:22.624  INFO 17132 --- [           main] com.dude.dms.updater.UpdateChecker       : Logservice wiederhergestellt
2020-05-03 23:08:24.294  INFO 17132 --- [           main] com.dude.dms.updater.UpdateDownloader    : Download gestartet
2020-05-03 23:08:24.306  INFO 17132 --- [           main] com.dude.dms.updater.UpdateDownloader    : Logservice wiederhergestellt
2020-05-03 23:09:04.080  INFO 17132 --- [nio-8888-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-03 23:09:04.081  INFO 17132 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-03 23:09:04.091  INFO 17132 --- [nio-8888-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2020-05-03 23:09:04.127  INFO 17132 --- [nio-8888-exec-1] c.v.f.s.DefaultDeploymentConfiguration   :
=================== Vaadin DeploymentConfiguration ====================

Vaadin is running in production mode.

=======================================================================
2020-05-03 23:09:04.213  INFO 17132 --- [nio-8888-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2020-05-03 23:09:04.324  INFO 17132 --- [           main] com.dude.dms.updater.UpdateDownloader    : Download abgeschlossen
2020-05-03 23:09:04.340  INFO 17132 --- [           main] com.dude.dms.updater.UpdateInstaller     : Entpacke Update
2020-05-03 23:09:04.354  INFO 17132 --- [           main] com.dude.dms.updater.UpdateInstaller     : Logservice wiederhergestellt
2020-05-03 23:09:04.366 ERROR 17132 --- [           main] com.dude.dms.updater.UpdateInstaller     : Das System kann den angegebenen Pfad nicht finden

java.io.IOException: Das System kann den angegebenen Pfad nicht finden
        at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_191]
        at java.io.File.createNewFile(Unknown Source) ~[na:1.8.0_191]
        at com.dude.dms.updater.UpdateInstaller.newFile(UpdateInstaller.kt:53) ~[classes!/:0.2.3]
        at com.dude.dms.updater.UpdateInstaller.install(UpdateInstaller.kt:28) ~[classes!/:0.2.3]
        at com.dude.dms.updater.UpdateDownloader$download$responseExtractor$1.extractData(UpdateDownloader.kt:30) [classes!/:0.2.3]
        at com.dude.dms.updater.UpdateDownloader$download$responseExtractor$1.extractData(UpdateDownloader.kt:18) [classes!/:0.2.3]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744) [spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) [spring-web-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
        at com.dude.dms.updater.UpdateDownloader.download(UpdateDownloader.kt:34) [classes!/:0.2.3]
        at com.dude.dms.updater.UpdateChecker.check(UpdateChecker.kt:69) [classes!/:0.2.3]
        at com.dude.dms.startup.StartUpRunner.run(StartUpRunner.kt:26) [classes!/:0.2.3]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar!/:2.2.4.RELEASE]
        at com.dude.dms.Application.main(Application.java:23) [classes!/:0.2.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [dms.jar:0.2.3]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [dms.jar:0.2.3]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [dms.jar:0.2.3]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [dms.jar:0.2.3]

2020-05-03 23:09:04.407  INFO 17132 --- [           main] com.dude.dms.brain.FileManager           : Generiere Ordner f³r Dokumente; docs
2020-05-03 23:09:04.410  INFO 17132 --- [           main] com.dude.dms.brain.FileManager           : Logservice wiederhergestellt
2020-05-03 23:09:04.419  INFO 17132 --- [           main] com.dude.dms.startup.StartUpRunner       : Cleaning up files...
2020-05-03 23:09:04.426  INFO 17132 --- [           main] com.dude.dms.startup.StartUpRunner       : DMS Gestartet
Warning: At the moment, your platform (Windows) is not supported by the official XGBoost maven package; ML-based suggestion reordering is disabled.



Error: Unable to access jarfile ./dms.jar
Drücken Sie die Eingabetaste, um den Vorgang fortzusetzen...:





```

**Comment by HeyDennis** [comment]
Auch ein manuelles kopieren etc. funktioniert nicht...

**Comment by axelvondreden** [comment]
> Es kommt ein leeres PS Fenster.

wie lange hast du es offen gelassen?
Dependencies werden beim ersten Start runter geladen, deshalb ist die jar ja nur 5MB groß

**Comment by axelvondreden** [comment]
Alternativ kannst du in der run.ps1 die erste Zeile ersetzen durch:
`java -jar "-Dthin.trace=true" "-Dvaadin.productionMode=true" ./dms.jar`
Dann sollte zumindest ein debug output kommen.

**Comment by HeyDennis** [comment]
läuft
