### ISSUE TITLE
Attributes for documents like tags

### ISSUE THREAD

**Issue by HeyDennis** [axelvondreden/dms#16]
Each document should be assinged defined attributes wich can be filled with values.
e.g.:  An invoice as document should get an attribute "Value" wich filled manuel. The value for the attribute "Value" is variable.

more examples for attributes : warranty, payment(Visa,Paypal...),language etc...

**Comment by HeyDennis** [comment]
Alles andere ist ja fertig und funktioniert tip tiop....

Aber das offene Thema fände ich schon nützlich

Rules

-    Möglichkeit Werte von Attributen zu setzen


Das "setzen" würde ich erstmal manuell machen per Eingabe
Bei gleichen Dokumenten wie Gehaltsabrechnung wäre eine Lage-Definition echt der Hammer...

**Comment by axelvondreden** [comment]
Bin auch schon länger am Überlegen.

Bei mir zum Beispiel:
Ein Attribut 'Betrag' in mehreren Tags vorhanden (Rechnung, Kontoauszug, ...)

Perfekt wäre es, wenn das System aufgrund von früheren Werten auf ähnlichen Dokumenten schon das richtige Wort finden könnte. Dazu muss ich es aber erstmal schaffen, dass ich Dokumente auf Ähnlichkeit überprüfen kann.

Ansonsten könnte man die Regeln sehr dynamisch aufbauen. z.B. für 'Betrag':
Nehme das Wort wenn...
( an letzter Stelle '€' steht **ODER** das nächste Wort 'eur' enthält ) **UND** ( in der selben Zeile das Wort 'Brutto' steht )

Genaueres kann ich noch nicht sagen

**Comment by HeyDennis** [comment]
hört sich gut an!

**Comment by HeyDennis** [comment]
Beim Regel erstellen kommt zuerst ein Fehler und dann die Erfolgsmeldung im Log: 
```

2020-08-24 17:32:06.412 ERROR 20988 --- [nio-8888-exec-1] c.v.flow.server.DefaultErrorHandler      :

org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: com.dude.dms.backend.data.docs.Attribute; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: com.dude.dms.backend.data.docs.Attribute
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:319) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178) ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:99) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at com.sun.proxy.$Proxy152.saveAndFlush(Unknown Source) ~[na:na]
        at com.dude.dms.backend.service.CrudService.save(CrudService.kt:11) ~[dms.jar:0.2.5]
        at com.dude.dms.backend.service.ConditionService.save(ConditionService.kt:11) ~[dms.jar:0.2.5]
        at com.dude.dms.ui.views.AttributeView.save(AttributeView.kt:92) ~[dms.jar:0.2.5]
        at com.dude.dms.ui.views.AttributeView.access$save(AttributeView.kt:31) ~[dms.jar:0.2.5]
        at com.dude.dms.ui.views.AttributeView$1$2$1.invoke(AttributeView.kt:61) ~[dms.jar:0.2.5]
        at com.dude.dms.ui.views.AttributeView$1$2$1.invoke(AttributeView.kt:31) ~[dms.jar:0.2.5]
        at com.github.mvysny.karibudsl.v10.VaadinComponentsKt$sam$com_vaadin_flow_component_ComponentEventListener$0.onComponentEvent(VaadinComponents.kt) ~[karibu-dsl-1.0.2.jar:na]
        at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:441) ~[flow-server-2.3.2.jar:2.3.2]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_191]
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:441) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:409) [flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:390) [flow-server-2.3.2.jar:2.3.2]
        at java.util.ArrayList.forEach(Unknown Source) ~[na:1.8.0_191]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:390) [flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:317) [flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.3.2.jar:2.3.2]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:108) ~[vaadin-spring-12.3.1.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_191]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_191]
Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: com.dude.dms.backend.data.docs.Attribute
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:127) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:726) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:694) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.spi.CascadingActions$7.cascade(CascadingActions.java:298) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:492) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:416) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:218) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:151) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:432) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:269) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:198) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:140) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:192) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:135) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:62) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:108) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:702) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:688) ~[hibernate-core-5.4.10.Final.jar:5.4.10.Final]
        at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:314) ~[spring-orm-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at com.sun.proxy.$Proxy131.persist(Unknown Source) ~[na:na]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:554) ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAndFlush(SimpleJpaRepository.java:569) ~[spring-data-jpa-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_191]
        at org.springframework.data.repository.core.support.ImplementationInvocationMetadata.invoke(ImplementationInvocationMetadata.java:72) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:382) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:205) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:549) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:155) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        ... 84 common frames omitted

2020-08-24 17:32:39.268  INFO 20988 --- [nio-8888-exec-3] com.dude.dms.ui.views.AttributeView      : Gespeichert
```

**Comment by HeyDennis** [comment]
Funktionieren tut es tortzdem !!!!!

**Comment by HeyDennis** [comment]
Naja okay... :-D

Also man kann keine Regel austragen / löschen...

Außerdem hat mein erster Test super funktioniert.
Beim 2. (2 Attribut Regeln aktiv) findet er nichts mehr.. 


```
2020-08-24 17:41:11.305  INFO 20988 --- [nio-8888-exec-2] com.dude.dms.brain.parsing.DocParser     : Found 1 possible values
2020-08-24 17:41:11.306  INFO 20988 --- [nio-8888-exec-2] com.dude.dms.brain.parsing.DocParser     : Found value: 1-02475
2020-08-24 17:41:11.308  INFO 20988 --- [nio-8888-exec-2] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:11.312  INFO 20988 --- [nio-8888-exec-2] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:34.066  INFO 20988 --- [io-8888-exec-10] com.dude.dms.ui.views.AttributeView      : Gespeichert
2020-08-24 17:41:37.620  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden: Firma
2020-08-24 17:41:37.621  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Suche Wert f³r Attribut: Name
2020-08-24 17:41:37.622  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Found 1 possible values
2020-08-24 17:41:37.627  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Found value: Dennis
2020-08-24 17:41:37.628  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Suche Wert f³r Attribut: Person
2020-08-24 17:41:37.630  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Found 1 possible values
2020-08-24 17:41:37.631  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Found value: 1-02475
2020-08-24 17:41:37.635  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:37.637  INFO 20988 --- [nio-8888-exec-1] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:42.796  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden: Firma
2020-08-24 17:41:42.798  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Suche Wert f³r Attribut: Name
2020-08-24 17:41:42.799  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Found 1 possible values
2020-08-24 17:41:42.803  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Found value: Dennis
2020-08-24 17:41:42.805  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Suche Wert f³r Attribut: Person
2020-08-24 17:41:42.806  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Found 1 possible values
2020-08-24 17:41:42.807  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Found value: 1-02475
2020-08-24 17:41:42.810  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:42.812  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:52.217  INFO 20988 --- [nio-8888-exec-9] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:52.219  INFO 20988 --- [nio-8888-exec-9] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:53.413  INFO 20988 --- [nio-8888-exec-7] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:41:53.417  INFO 20988 --- [nio-8888-exec-7] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:09.337  INFO 20988 --- [io-8888-exec-10] com.dude.dms.ui.views.AttributeView      : Gespeichert
2020-08-24 17:42:13.128  INFO 20988 --- [nio-8888-exec-4] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:13.132  INFO 20988 --- [nio-8888-exec-4] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:13.984  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:13.986  INFO 20988 --- [nio-8888-exec-6] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:14.220  INFO 20988 --- [nio-8888-exec-9] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:14.223  INFO 20988 --- [nio-8888-exec-9] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:24.189  INFO 20988 --- [nio-8888-exec-4] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:24.192  INFO 20988 --- [nio-8888-exec-4] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:54.546  INFO 20988 --- [nio-8888-exec-8] com.dude.dms.ui.views.AttributeView      : Gespeichert
2020-08-24 17:42:56.355  INFO 20988 --- [nio-8888-exec-5] com.dude.dms.ui.views.AttributeView      : Gespeichert
2020-08-24 17:42:59.952  INFO 20988 --- [io-8888-exec-10] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:42:59.955  INFO 20988 --- [io-8888-exec-10] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:43:02.833  INFO 20988 --- [nio-8888-exec-7] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:43:02.836  INFO 20988 --- [nio-8888-exec-7] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:43:06.317  INFO 20988 --- [nio-8888-exec-5] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
2020-08-24 17:43:06.319  INFO 20988 --- [nio-8888-exec-5] com.dude.dms.brain.parsing.DocParser     : Kategorien gefunden:
```

**Comment by HeyDennis** [comment]
Wäre auch cool wenn man mehrere Fälle einstellen kann. 
(wie bei den Kategorieregeln)

**Comment by HeyDennis** [comment]
Funktioniert echt gut !

Ein paar kleine Fehler:
- wenn ein Dokument bereits die Kategorie besitzt und ich füge ein Attribut hinzu oder ändere dies wird die Regel nicht ausgeführt. Beim Import neuer Dokumente klappt es. Zusätzlich die Start Funktion evtl. auch beim Attribut hinzufügen 
- der Bedingungsdropdown wird teilweise überlagert 
![grafik](https://user-images.githubusercontent.com/47058862/132689358-b69b5693-04ba-4e33-ae13-39f9e7e9ccc7.png)
- beim Bedingungsdropdown kommt ein Oder als Auswahl -> man muss aber ein or eingeben
